# Projeto Final - Machine Learning e Visão Computacional

## Predição de Risco de Crédito

---

## Objetivo

Desenvolver um pipeline completo de Machine Learning capaz de prever clientes com risco de inadimplência, passando pelas etapas de coleta dos dados, exploração, limpeza, preparação, treinamento e avaliação dos modelos.

---

## Pipeline do Projeto

1. Coleta de Dados
2. Limpeza Estrutural e Exploração
3. Divisão dos Dados
4. Pré-processamento
5. Treinamento do Modelo
6. Avaliação e Validação

# 1. Coleta de Dados

Nesta etapa será realizada a importação das bibliotecas necessárias para o projeto, o carregamento da base de dados e uma primeira inspeção da estrutura do dataset.

## 1.1 Importação das Bibliotecas

In [10]:
# =====================================================
# Bibliotecas para manipulação de dados
# =====================================================

import pandas as pd
import numpy as np

# =====================================================
# Bibliotecas para visualização
# =====================================================

import matplotlib.pyplot as plt
import seaborn as sns

# =====================================================
# Configuração dos gráficos
# =====================================================

plt.style.use("ggplot")
sns.set_theme(style="whitegrid")

# =====================================================
# Configuração geral
# =====================================================

import warnings

warnings.filterwarnings("ignore")

## 1.2 Carregamento da Base de Dados

Nesta etapa será realizada a leitura do dataset utilizando a biblioteca Pandas e uma verificação inicial para garantir que os dados foram carregados corretamente.

In [11]:
# =====================================================
# Carregamento da base de dados
# =====================================================

caminho_dados = "../data/raw/credit_risk_dataset.csv"

df = pd.read_csv(caminho_dados)

In [12]:
print("Base carregada com sucesso!")
print("Primeiros registros:")
display(df.head())
print("Ultimos registros:")
display(df.tail())
print("Registros aleatórios:")
display(df.sample(5))

linhas, colunas = df.shape
print(f"Quantidade de linhas : {linhas}")
print(f"Quantidade de colunas: {colunas}")

for coluna in df.columns:
    print(coluna)

Base carregada com sucesso!
Primeiros registros:

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

Ultimos registros:

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30

Registros aleatórios:

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
28717,29,54000,MORTGAGE,8.0,VENTURE,D,14800,15.31,1,0.27,Y,5
8029,24,49000,MORTGAGE,0.0,MEDICAL,B,5000,12.18,1,0.10,N,3
27926,27,58000,RENT,11.0,VENTURE,A,7000,NaN,0,0.12,N,9
25260,29,47500,RENT,0.0,PERSONAL,A,12000,8.94,0,0.25,N,5
31917,38,37440,RENT,14.0,VENTURE,C,19750,13.92,1,0.53,N,16

Quantidade de linhas : 32581
Quantidade de colunas: 12
person_age
person_income
person_home_ownership
person_emp_length
loan_intent
loan_grade
loan_amnt
loan_int_rate
loan_status
loan_percent_income
cb_person_default_on_file
cb_person_cred_hist_length

### Primeiras observações

Após o carregamento da base foi possível verificar que o dataset contém informações relacionadas ao perfil financeiro dos clientes e às características dos empréstimos concedidos.

As variáveis incluem informações demográficas, renda anual, finalidade do empréstimo, classificação de crédito, taxa de juros e histórico financeiro.

A variável **loan_status** representa o alvo do problema de classificação, indicando se o cliente tornou-se inadimplente (1) ou permaneceu adimplente (0).

Nesta etapa foi confirmado que o arquivo foi carregado corretamente e que a estrutura da base está íntegra para prosseguirmos com a análise exploratória.